In [8]:
import numpy as np

In [9]:
# from list to np.array
mylist = [1, 2, 3]
type(mylist)

list

In [10]:
np_arr = np.array(mylist)
type(np_arr)

numpy.ndarray

In [11]:
# A list o tree lists in python becomes a 3x3 matrix with np.array
my_list = [[1,2,3],[4,5,6],[7,8,9]]
np_matrix = np.array(my_list)

In [12]:
print(np_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np_matrix.shape

(3, 3)

In [14]:
# numpy array from 0 to 10 [0, 12) excluding 12 including 0
arrange = np.arange(0, 12, 1)
print(arrange)
print(type(arrange))
print(len(arrange))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
12


In [15]:
# creating an array of zeros (type of zeros is float)
npz = np.zeros((2,2))
print(npz)
print(type(npz[0][0]))

[[0. 0.]
 [0. 0.]]
<class 'numpy.float64'>


In [16]:
# creating an array of ones
np_ones = np.ones((2,2))
print(np_ones)

[[1. 1.]
 [1. 1.]]


In [17]:
# numpy broadcasting
np.ones((3,3))*4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [18]:
# evenly spaced np array [0,10]
np.linspace(0,10,11) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
# create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# random numpy library
# random sample (numbers) from a uniform distribution over zero and one
# every number between 0, and 1 has the same probability of getting chosen
np.random.rand(4,4)

array([[0.0911123 , 0.06686913, 0.54910248, 0.27198122],
       [0.9133344 , 0.60978747, 0.02639351, 0.1732951 ],
       [0.37628099, 0.10195452, 0.17552217, 0.61181626],
       [0.86904605, 0.88898508, 0.66582823, 0.70279576]])

In [23]:
# random sample from a normal distribution over zero and one
# a normal distribution has a mean of (0) and standard deviation at 1. This means that the numbers returned are between -1 and 1
np.random.randn(3,3)

array([ 0.29213477,  0.71465945, -0.03864481])