In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.2.2+cpu'

In [6]:
arr = np.array(range(1,6))
print(arr)

[1 2 3 4 5]


In [9]:
# create a tensor pointing the same memory location than the np array
x = torch.from_numpy(arr)
# torch.as_tensor(arr)
type(x)

torch.Tensor

In [10]:
# creating a torch 2d tensor from nparray (pointing the same memory location)
arr2d = np.arange(0.0, 12.0).reshape(4, 3)

In [11]:
x2 = torch.from_numpy(arr2d)

In [12]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [13]:
arr[0] = 99

In [14]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [17]:
# creating a working copy
my_arr = np.arange(0,10)
my_tensor = torch.tensor(my_arr) #integer tensor
my_tensor_f = torch.Tensor(my_arr) #flotating point tensor

In [20]:
my_tensor.dtype

torch.int32

In [19]:
my_tensor_f.dtype

torch.float32

In [23]:
# creating tensors with torch
# uninitialized tensor (block of memory of size of the tensor)
torch.empty(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
# zeros tensor 
torch.zeros(4,2, dtype=torch.int32)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [ ]:
torch.ones()