In [2]:
import torch
import numpy as np

In [3]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [4]:
type(x[1,1])

torch.Tensor

In [5]:
# returns a 1d tensor
x[:,1]

tensor([1, 3, 5])

In [6]:
# returns a column tensor (column vector) (used often)
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [7]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
z = x.view(2, 5)

In [13]:
y = x.reshape(2, 5)

In [14]:
x[0] = 9999

In [16]:
print(z)
print(y)

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
