In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [3]:
type(x[1,1])

torch.Tensor

In [4]:
# returns a 1d tensor
x[:,1]

tensor([1, 3, 5])

In [5]:
# returns a column tensor (column vector) (used often)
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [6]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
x.view(2, 5)