In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [3]:
type(x[1,1])

torch.Tensor

In [4]:
# returns a 1d tensor
x[:,1]

tensor([1, 3, 5])

In [5]:
# returns a column tensor (column vector) (used often)
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [6]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [7]:
z = x.view(2, 5)

In [8]:
y = x.reshape(2, 5)

In [9]:
x[0] = 9999

In [10]:
print(z)
print(y)

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [11]:
torch.cuda.is_available()

True

In [12]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1070'

In [16]:
a = torch.arange(3)
b = torch.arange(3)

In [17]:
c = torch.add(a, b)

In [18]:
print(c)

tensor([0, 2, 4])


In [19]:
print(a)
a.mul_(b) # re-assigns the value of a with the multiplication of a and b
print(a)

tensor([0, 1, 2])
tensor([0, 1, 4])


In [23]:
x = torch.randint(0, 10, (3, 3))
y = torch.randint(0, 10, (3, 3))
print(x, y)

tensor([[6, 1, 8],
        [9, 8, 1],
        [2, 1, 6]]) tensor([[0, 7, 3],
        [5, 0, 5],
        [5, 8, 9]])


In [24]:
z = torch.mm(x, y) #also valid a @ b
print(z)

tensor([[ 45, 106,  95],
        [ 45,  71,  76],
        [ 35,  62,  65]])


In [26]:
z_dot = torch.dot(a, b)
print(z_dot)

tensor(9)


In [30]:
a = torch.randn(3, 3)
a.norm()

tensor(2.3728)